[build]
  command = "npm run build && npm run export"
  publish = "out"

[[plugins]]
  package = "/netlify/plugins/demo-restaurant-data-contentful"

  [plugins.inputs]
    # Directory for the generated JSON data files to reside in
    dataDir = "data"